### PR TITLE
Another "explicit any" fix in an exported class

### PR DESCRIPTION
**Pull request by vzwick**
Sorry for the confusion. I unfortunately can't wrap my head around how one would make this scenario testable.

### CODE REVIEW

**Comment by xpepermint** [comment]
No problem, let's fix it :). 

Tests and the examples uses package's `noImplicitAny` setting. We could set this to `true` but we have more work then.

**Comment by xpepermint** [comment]
Let me do this for you ...

**Comment by xpepermint** [comment]
Publish to NPM: rawmodel@1.8.4

This should do the trick.

**Comment by xpepermint** [comment]
Let me know if this now works well for you ...

**Comment by vzwick** [comment]
@xpepermint - Thanks Kristijan, much appreciated!

**Comment by xpepermint** [comment]
Thank you.

**Pull request merged**
